### ISSUE TITLE
一些部署上的问题

### ISSUE THREAD

**Issue by CainYzb** [EvanLuo42/oliver#2]
![image](https://github.com/EvanLuo42/oliver/assets/50669073/92838a94-ade8-4369-8072-382225a47c8a)
我是一个小白，没有学过前端，你的主题十分的简洁高效，但是在我按照指导部署之后却发生了意外。想得到更加丰富的ReadMe!!!再次感谢作者

**Comment by EvanLuo42** [comment]
```
favicon: favicon url
avatar: avatar url

menu:
  Home: /
  Archives: /archives
  About: /about

copyright: copyright

gitalk:
  client_id: 
  client_secret: 
  repo: 
  owner: 
```

这边需要填入你自己的相关信息。然后. `_config_template.yml` 要改成 `config.yml`。
